#!/bin/sh
SRC=$HOME/projects/ob-kourin-system
RAM=/Volumes/ramdisk
SERIAL=/dev/tty.usbserial-A6008c9y
CAMERA_SERVER=http://192.168.1.2:8784/

mount_ramdisk && cp -R $SRC/camera/processing/simple_camera/application.macosx/simple_camera.app $RAM/kourin_camera.app
open $RAM/kourin_camera.app &
ruby $SRC/camera-server/uploader.rb -f $RAM/camera.jpg -u $CAMERA_SERVER -i 1 -loop &
$SRC/robot-http-server/robot-http-server $SERIAL -bps 4800 -post_interval 1000 &
